op: sample_data

data:
  data_dir: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/deep_learning_denoising/renderings
  tfrecord_dir: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/renderings_tfrecords_diffuse
  scenes:
    - bathroom2
    - car2
    - classroom
    - house
    - room2
    - spaceship
    - staircase
    - room3
  splits:
    train:      0.90
    validation: 0.05
    test:       0.05
  in_spp: 256
  gt_spp: 8192
  parse_start: 0
  parse_step: 2
  parse_shuffle: False
  patch_size: 65
  patches_per_im: 10
  save_debug_ims: True
  diff_var_weight: 1.0
  spec_var_weight: 0.0
  shuffle_buffer_size_limit: 50000

train_params:
  batch_size: 5
  learning_rate: 1e-5
  max_epochs: 100
  log_freq: 100
  save_freq: 10000
  viz_freq: 1
  block_on_viz: False
  summary_dir: summaries
  checkpoint_dir: checkpoints
  fp16: False

kpcn:
  diff:
    include: True
    restore_path: /home/owen/workspace/metro/scripts/checkpoints/diff/var-59999
  spec:
    include: False
    restore_path: x

layers:
  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  # - type: batch_normalization

  # output
  - type: conv2d
    num_outputs: 441  # 21 * 21
    kernel_size: 5
    stride: 1
    padding: same
