op: train

data:
  data_dir: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/deep_learning_denoising/renderings
  tfrecord_dir: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/renderings_tfrecords_partition
  scenes:
    - bathroom2
    # - car2
    # - classroom
    # - house
    # - room2
    # - spaceship
    # - staircase
    # - room3
  splits:
    train:      0.90
    validation: 0.05
    test:       0.05
  in_spp: 256
  gt_spp: 8192
  parse_start: 0
  parse_step: 1
  parse_shuffle: True
  file_example_limit: 500
  patch_size: 65
  patches_per_im: 400
  save_debug_ims: True
  save_debug_ims_every: 10
  color_var_weight: 1.0
  normal_var_weight: 1.0
  shuffle_buffer_size_limit: 10000
  shuffle_filenames: True
  clip_ims: False

train_params:
  batch_size: 5
  learning_rate: 1e-4
  reset_lr: True
  max_epochs: 1e4
  log_freq: 100
  save_freq: 10000
  viz_freq: 1
  block_on_viz: False
  summary_dir: summaries
  checkpoint_dir: checkpoints
  fp16: False

kpcn:
  diff:
    train_include: True
    # restore_path: /home/owen/workspace/metro/scripts/checkpoints/diff_saved/var-169999
  spec:
    train_include: False
    # restore_path: /home/owen/workspace/metro/scripts/checkpoints/spec_saved/var-39999

evaluate:
  im_path: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/deep_learning_denoising/renderings/bathroom2/18889126-00256spp.exr
  out_dir: out

layers:
  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  - type: conv2d
    num_outputs: 100
    kernel_size: 5
    stride: 1
    padding: same
    activation: relu

  - type: batch_normalization

  # output
  - type: conv2d
    num_outputs: 441  # 21 * 21
    kernel_size: 5
    stride: 1
    padding: same
