op: train
# train, sample_data, visualize_data, denoise, compute_error

data:
  data_dir: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/deep_learning_denoising/renderings
  tfrecord_dir:
    - /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/renderings_tfrecords
    - /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/renderings_tfrecords_partition
    - /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/renderings_tfrecords_partition_128
    - /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/renderings_tfrecords_partition_spec
  scenes:
    - bathroom2
    - car2
    - classroom
    - house
    - room2
    - spaceship
    - staircase
    - room3
  splits:
    train:      0.95
    validation: 0.05
    test:       0.00
  in_spp: 256
  gt_spp: 8192
  parse_start: 0
  parse_step: 1
  parse_shuffle: True
  file_example_limit: 300
  patch_size: 65  # 125
  patches_per_im: 500
  save_debug_ims: True
  save_debug_ims_every: 50
  color_var_weight: 1.0
  normal_var_weight: 1.0
  shuffle_buffer_size_limit: 5000
  shuffle_filenames: True
  clip_ims: False
  use_error_maps_for_sampling: True

train_params:
  batch_size: 12
  learning_rate: 1e-4
  reset_lr: True
  max_epochs: 1e4
  log_freq: 100
  save_freq: 2000
  save_best: False  # if True, ignores `save_freq`
  viz_freq: 1
  block_on_viz: False
  summary_dir: summaries
  checkpoint_dir: checkpoints
  fp16: False
  clip_by_global_norm: False  # empirically not helpful
  asymmetric_loss: True

kpcn:
  diff:
    train_include: True
    # restore_path: /home/owen/workspace/metro/scripts/checkpoints/diff_saved/var-169999
    # restore_path: /home/owen/workspace/metro/scripts/checkpoints/diff/var-23999
  spec:
    train_include: False
    # restore_path: /home/owen/workspace/metro/scripts/checkpoints/spec_saved/var-409999
    restore_path: /home/owen/workspace/metro/scripts/checkpoints/spec/var-3999
  valid_padding: False  # during training only

evaluate:
  im_path: /media/owen/302371f7-852e-4f78-94e6-4d3ffebda36e/deep_learning_denoising/renderings/bathroom2/18889126-00256spp.exr
  out_dir: out
  write_error_ims: False
  viz_kernels: True

layers:
  - type: conv2d
    kernel_init: xavier
    num_outputs: 100
    kernel_size: 3
    stride: 1
    activation: relu

  - type: conv2d
    kernel_init: xavier
    num_outputs: 100
    kernel_size: 3
    stride: 1
    activation: x

  - type: residual_block
    kernel_init: xavier
    num_outputs: 100
    kernel_size: 3
    dropout_keep_prob: 0.9  # to omit, use "x"
    chain: 12

  - type: conv2d
    kernel_init: xavier
    num_outputs: 100
    kernel_size: 1
    stride: 1
    activation: relu

  # output
  - type: conv2d
    kernel_init: xavier
    num_outputs: 441  # 21 * 21
    kernel_size: 1
    stride: 1
